name: version_manipulation
version: 0.1.0
homepage: https://github.com/f3ath/dart-version-manipulation
description: Extension on Dart `pub_semver` library. Provides `nextBuild`, `nextPreRelease` and `change`.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pub_semver: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.0
  coverage: ^1.0.1
  check_coverage: ^0.0.2

